name: "Setup CumulusCI Environment"
description: "Setup a CumulusCI environment for running cci commands."
author: "Atlas Assistance Dogs"

runs:
  using: "composite"
  steps:
    - name: Install sf cli
      shell: bash
      run: |
        npm install @salesforce/cli --global
        sf version

    - name: "Authenticate dev hub using SFDX_AUTH_URL"
      shell: bash
      env:
        DEV_HUB_AUTH_URL: ${{ secrets.DEV_HUB_AUTH_URL }}
      run:
          echo $DEV_HUB_AUTH_URL | sf org login sfdx-url -d -a devhub -u
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install CumulusCI
      shell: bash
      run: |
        python -m pip install -U pip
        pip install cumulusci
        cci version
    - name: Connect GitHub service
      shell: bash
      run: |
        cci service connect github --username ${{ inputs.GITHUB_USERNAME }} --token ${{ inputs.GITHUB_PAT }} --email ${{ inputs.GITHUB_EMAIL }}
