npe4__Relationship_Lookup__c:
    Aunt:
        npe4__Male__c: Nephew
        npe4__Female__c: Niece
        npe4__Neutral__c: Sibling's Child
    Boyfriend:
        npe4__Male__c: Boyfriend
        npe4__Female__c: Girlfriend
        npe4__Neutral__c: Partner
    Brother:
        npe4__Male__c: Brother
        npe4__Female__c: Sister
        npe4__Neutral__c: Sibling
    Child:
        npe4__Male__c: Father
        npe4__Female__c: Mother
        npe4__Neutral__c: Parent
    Cousin:
        npe4__Male__c: Cousin
        npe4__Female__c: Cousin
        npe4__Neutral__c: Cousin
    Daughter:
        npe4__Male__c: Father
        npe4__Female__c: Mother
        npe4__Neutral__c: Parent
    Employee:
        npe4__Male__c: Employer
        npe4__Female__c: Employer
        npe4__Neutral__c: Employer
    Employer:
        npe4__Male__c: Employee
        npe4__Female__c: Employee
        npe4__Neutral__c: Employee
    Family:
        npe4__Male__c: Family
        npe4__Female__c: Family
        npe4__Neutral__c: Family
    Father:
        npe4__Male__c: Son
        npe4__Female__c: Daughter
        npe4__Neutral__c: Child
    Girlfriend:
        npe4__Male__c: Boyfriend
        npe4__Female__c: Girlfriend
        npe4__Neutral__c: Partner
    Grandchild:
        npe4__Male__c: Grandfather
        npe4__Female__c: Grandmother
        npe4__Neutral__c: Grandparent
    Granddaughter:
        npe4__Male__c: Grandfather
        npe4__Female__c: Grandmother
        npe4__Neutral__c: Grandparent
    Grandfather:
        npe4__Male__c: Grandson
        npe4__Female__c: Granddaughter
        npe4__Neutral__c: Grandchild
    Grandmother:
        npe4__Male__c: Grandson
        npe4__Female__c: Granddaughter
        npe4__Neutral__c: Grandchild
    Grandparent:
        npe4__Male__c: Grandson
        npe4__Female__c: Granddaughter
        npe4__Neutral__c: Grandchild
    Granddson:
        npe4__Male__c: Grandfather
        npe4__Female__c: Grandmother
        npe4__Neutral__c: Grandparent
    Guardian:
        npe4__Male__c: Ward
        npe4__Female__c: Ward
        npe4__Neutral__c: Ward
    Handler:
        npe4__Male__c: Client
        npe4__Female__c: Client
        npe4__Neutral__c: Client
    Husband:
        npe4__Male__c: Husband
        npe4__Female__c: Wife
        npe4__Neutral__c: Spouse
    Mother:
        npe4__Male__c: Son
        npe4__Female__c: Daughter
        npe4__Neutral__c: Child
    Nephew:
        npe4__Male__c: Uncle
        npe4__Female__c: Aunt
        npe4__Neutral__c: Parent's Sibling
    Niece:
        npe4__Male__c: Uncle
        npe4__Female__c: Aunt
        npe4__Neutral__c: Parent's Sibling
    Parent:
        npe4__Male__c: Son
        npe4__Female__c: Daughter
        npe4__Neutral__c: Child
    Partner:
        npe4__Male__c: Partner
        npe4__Female__c: Partner
        npe4__Neutral__c: Partner
    Primary Emergency Contact:
        npe4__Male__c: Contact
        npe4__Female__c: Contact
        npe4__Neutral__c: Contact
    Secondary Emergency Contact:
        npe4__Male__c: Contact
        npe4__Female__c: Contact
        npe4__Neutral__c: Contact
    Sibling:
        npe4__Male__c: Brother
        npe4__Female__c: Sister
        npe4__Neutral__c: Sibling
    Sister:
        npe4__Male__c: Brother
        npe4__Female__c: Sister
        npe4__Neutral__c: Sibling
    Son:
        npe4__Male__c: Father
        npe4__Female__c: Mother
        npe4__Neutral__c: Parent
    Spouse:
        npe4__Male__c: Spouse
        npe4__Female__c: Spouse
        npe4__Neutral__c: Spouse
    TA:
        npe4__Male__c: Student
        npe4__Female__c: Student
        npe4__Neutral__c: Student
    Team Facilitator:
        npe4__Male__c: Client
        npe4__Female__c: Client
        npe4__Neutral__c: Client
    Team Facilitator Lead:
        npe4__Male__c: Client
        npe4__Female__c: Client
        npe4__Neutral__c: Client
    Uncle:
        npe4__Male__c: Nephew
        npe4__Female__c: Niece
        npe4__Neutral__c: Sibling's Child
    Wife:
        npe4__Male__c: Husband
        npe4__Female__c: Wife
        npe4__Neutral__c: Spouse
AtlasSettings__c:
    - location: org
      data:
          DogExamRenewalYears__c: 1
          LinkFilesToTeamMembers__c: True
          PageSize__c: 50
          RabiesRenewalYears__c: 3
          VaccineRenewalYears__c: 1
          BackgroundCheckRenewalYears__c: 1
