import { createElement } from "lwc";
import EditCeuCmp from "c/editCeuCmp";
import CEU_OBJECT from "@salesforce/schema/CEU__c";

describe("c-edit-ceu-cmp", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const RECORD_ID_INPUT = "0031700000pJRRSAA4";
    const element = createElement("c-edit-ceu-cmp", { is: EditCeuCmp });
    element.recordId = "0031700000pJRRSAA4";//RECORD_ID_INPUT;
    element.objectApiName = CEU_OBJECT.objectApiName;

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
