name: 'Install SFDX'
description: 'Install python, and sfdx'
inputs:
  auth_url:  # id of input
    description: 'SFDX auth url'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Install sfdx
      shell: bash
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        ./sfdx/install
        echo ${{ auth_url }} > sfdx_auth
        sfdx auth:sfdxurl:store -f sfdx_auth -d