public with sharing class ExtraCode {
    /*
    <div class="slds-form-element slds-form-element_edit slds-form-element_readonly slds-hint-parent">
        <label class="slds-form-element__label" for="form-element-05">{vaccinationName}</label>
        <div class="slds-form-element__control">
            <div class="slds-medium-show_inline-block slds-form-element__static redColor">{vaccinationDate}</div>
            <button class="slds-button slds-button_icon" title="Edit: Date">
                <svg class="slds-button__icon slds-button__icon_hint" aria-hidden="true">
                    <use xlink:href="/_slds/icons/utility-sprite/svg/symbols.svg#edit"></use>
                </svg>
                <span class="slds-assistive-text">Edit: Date</span>
            </button>  
        </div>    
    </div>
    <template if:true = {isExpired}>
        <div class="slds-form-element__help red" id="form-error-01">Date is expired</div> 
    </template>
    */
}