public inherited sharing class RelationshipService implements IRelationshipService {
    public RelationshipService() {

    }
    public List<npe4__Relationship__c> getByContact(Id recordId) {
        return null;
    }
    public List<npe4__Relationship__c> getByRelatedContact(Id recordId) {
        return null;
    }
    public List<npe4__Relationship__c> getByContactAndType(Id recordId, string type) {
        return null;
    }
}