name: Deploy to scratch org and test

on:
  push:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Authenticate using SFDX_AUTH_URL"
        run: |
          echo ${{ secrets.DEV_HUB_AUTH_URL }} | sf org login sfdx-url -d -a devhub -u

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install CumulusCI
        shell: bash
        run: |
          python -m pip install -U pip
          pip install cumulusci
          pip install --upgrade cumulusci
          cci version

      - name: connect to dev hub
        shell: bash
        run: cci org import devhub dev_hub

      - name: Upload to a scratch org
        shell: bash
        run: cci flow run ci_feature --org dev
