name: Feature Test
on:
    push:
        branches:
            - dev
            - main
    workflow_dispatch:
jobs:
    feature-test:
        name: "Feature Test"
        # Replace this URL with your forked repo.
        # Use the feature test workflow that matches your project needs.
        uses: Atlas-Assistance-Dogs/standard-cci-workflows/.github/workflows/feature.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
