name: Deploy to Sandbox

on:
    push:
        branches:
            - dev
            - feature/3-github-actions

env:
    CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
    CUMULUSCI_ORG_SANDBOX: ${{ secrets.CUMULUSCI_ORG_SANDBOX }}

jobs:
    deploy_to_sandbox:
        name: "Deploy to sandbox"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install sfdx
              run: |
                  mkdir sfdx
                  wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
                  ./sfdx/install
                  echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
                  sfdx auth:sfdxurl:store -f sfdx_auth -d
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: "3.8"
            - name: Install CumulusCI
              run: |
                  python -m pip install -U pip
                  pip install cumulusci
            - name: Deploy source
              run: |
                  cci flow run sandbox --org sandbox
